SELECT L.NOMBRE, SUB.LOCALIDAD, AVG(ESTUDIOS) MEDIA FROM
(SELECT NOMBRECOMPLETO, ESTUDIOSSUPERIORES, LOCALIDAD, DECODE(ESTUDIOSSUPERIORES,
  'Ninguno', 1, 
  'Basicos', 2, 
  'Superiores', 3,
  'Doctorado', 4) ESTUDIOS
FROM VOTANTES) SUB, LOCALIDADES L
WHERE SUB.LOCALIDAD=L.IDLOCALIDAD 
GROUP BY L.NOMBRE, SUB.LOCALIDAD
ORDER BY MEDIA DESC;
