SELECT V.NOMBRECOMPLETO, V.SITUACIONLABORAL, COUNT(C.VOTANTE) "VECES" FROM CONSULTAS C, VOTANTES V
WHERE C.VOTANTE=V.DNI AND V.SITUACIONLABORAL='Activo'
GROUP BY V.NOMBRECOMPLETO, V.SITUACIONLABORAL
HAVING COUNT(C.VOTANTE)<(SELECT AVG(COUNT(VOTANTE)) FROM CONSULTAS
GROUP BY VOTANTE)
ORDER BY "VECES" DESC;
