SELECT L.NOMBRE, SUB1.LOCALIDAD, SUB1.MEDIAL FROM LOCALIDADES L,
(SELECT LOCALIDAD, AVG(DECODE(ESTUDIOSSUPERIORES,
  'Ninguno', 1, 
  'Basicos', 2, 
  'Superiores', 3,
  'Doctorado', 4)) MEDIAL
FROM VOTANTES V, LOCALIDADES L
WHERE V.LOCALIDAD=L.IDLOCALIDAD
GROUP BY LOCALIDAD) SUB1
WHERE SUB1.LOCALIDAD=L.IDLOCALIDAD
AND SUB1.MEDIAL>ALL(SELECT AVG(DECODE(ESTUDIOSSUPERIORES,
  'Ninguno', 1, 
  'Basicos', 2,  
  'Superiores', 3,
  'Doctorado', 4, -1)) ESTUDIOSP
FROM VOTANTES, LOCALIDADES
WHERE VOTANTES.LOCALIDAD=LOCALIDADES.IDLOCALIDAD
GROUP BY PROVINCIA);

