SELECT NOMBRECOMPLETO, DNI, LOCALIDAD FROM VOTANTES
WHERE SUBSTR(DNI,-1,1)=LOCALIDAD+1;

SELECT NOMBRECOMPLETO, DNI, LOCALIDAD FROM VOTANTES
WHERE SUBSTR(DNI, LENGTH(DNI)-LENGTH(LOCALIDAD)+1)=LOCALIDAD+1;