SELECT C.VOTANTE, V.NOMBRECOMPLETO, COUNT(C.VOTANTE) "VECES" FROM CONSULTAS C, VOTANTES V
WHERE C.VOTANTE=V.DNI AND V.FECHANACIMIENTO!=(SELECT MIN(FECHANACIMIENTO) FROM VOTANTES 
WHERE FECHANACIMIENTO>(SELECT MIN(FECHANACIMIENTO) FROM VOTANTES))
GROUP BY C.VOTANTE, V.NOMBRECOMPLETO
ORDER BY "VECES" DESC;
