SELECT P.SIGLAS, COUNT(ER.PARTIDO) FROM PARTIDOS P, EVENTOS_RESULTADOS ER
WHERE P.IDPARTIDO=ER.PARTIDO
GROUP BY P.SIGLAS
HAVING COUNT(ER.PARTIDO)=(SELECT MAX(COUNT(PARTIDO)) FROM EVENTOS_RESULTADOS
GROUP BY PARTIDO);

