SELECT NOMBRE FROM LOCALIDADES
WHERE NUMEROHABITANTES>(SELECT L.NUMEROHABITANTES FROM LOCALIDADES L, VOTANTES V
WHERE L.IDLOCALIDAD=V.LOCALIDAD AND V.FECHANACIMIENTO=(SELECT MIN(FECHANACIMIENTO) FROM VOTANTES
WHERE FECHANACIMIENTO>(SELECT MIN(FECHANACIMIENTO) FROM VOTANTES)));