SET SERVEROUTPUT ON;
 DROP TABLE VOTANTESANTIGUOS;
 CREATE TABLE VOTANTESANTIGUOS AS SELECT * FROM VOTANTES WHERE FECHANACIMIENTO<'1/1/1980';
 ALTER TABLE VOTANTESANTIGUOS ADD SUELDO NUMBER(10) DEFAULT 0;
 UPDATE VOTANTESANTIGUOS
 SET SUELDO=1500
 WHERE SITUACIONLABORAL='Activo';
