 UPDATE VOTANTESANTIGUOS
 SET SUELDO=1500
 WHERE SITUACIONLABORAL='Activo';
 
 UPDATE VOTANTESANTIGUOS
 SET SUELDO=1000
 WHERE SITUACIONLABORAL='Jubilado';
 
 UPDATE VOTANTESANTIGUOS
 SET SUELDO=SUELDO+100
 WHERE ESTUDIOSSUPERIORES='Ninguno' AND SITUACIONLABORAL='Activo';
 
 UPDATE VOTANTESANTIGUOS
 SET SUELDO=SUELDO+200
 WHERE ESTUDIOSSUPERIORES='Basicos'  AND SITUACIONLABORAL='Activo';
 
 UPDATE VOTANTESANTIGUOS
 SET SUELDO=SUELDO+300
 WHERE ESTUDIOSSUPERIORES='Superiores' AND SITUACIONLABORAL='Activo';
 
 UPDATE VOTANTESANTIGUOS
 SET SUELDO=SUELDO+1000
 WHERE ESTUDIOSSUPERIORES='Doctorados' AND SITUACIONLABORAL='Activo';