SET SERVEROUTPUT ON;
DECLARE
  CURSOR DNIS IS 
  SELECT DNI FROM VOTANTES ORDER BY DNI DESC;
  DNIANTERIOR VOTANTES.DNI%TYPE;
  
BEGIN
  FOR UNDNI IN DNIS LOOP
    IF DNIS%ROWCOUNT>1 THEN
      DBMS_OUTPUT.PUT_LINE(DNIANTERIOR|| ' va antes que ' ||UNDNI.DNI);
    END IF;
      DNIANTERIOR:=UNDNI.DNI;
  END LOOP;
  DBMS_OUTPUT.PUT_LINE('El menor es:'||DNIANTERIOR);
END;