SET SERVEROUTPUT ON;
DECLARE
  TYPE TABLA_HASH IS TABLE OF FLOAT INDEX BY VARCHAR2(100);
  MITABLA TABLA_HASH;
  KEY VARCHAR2(100);
  CURSOR RESULTADOS IS 
  SELECT NOMBRECOMPLETO, RESULTADO FROM PARTIDOS P, EVENTOS_RESULTADOS E
  WHERE P.IDPARTIDO=E.PARTIDO;
BEGIN
  FOR I IN RESULTADOS LOOP
    IF NOT MITABLA.EXISTS(I.NOMBRECOMPLETO) THEN
      MITABLA(I.NOMBRECOMPLETO):=I.RESULTADO;
    ELSE
      MITABLA(I.NOMBRECOMPLETO):=MITABLA(I.NOMBRECOMPLETO)+I.RESULTADO;
    END IF;
  END LOOP;
  KEY:=MITABLA.FIRST;
  WHILE KEY IS NOT NULL LOOP
    DBMS_OUTPUT.PUT_LINE(KEY || ' => ' || MITABLA(KEY));
    KEY:=MITABLA.NEXT(KEY);
  END LOOP;
END;