SET SERVEROUTPUT ON;
DECLARE
  CURSOR c IS SELECT * FROM PARTIDOS;
  NOMBRE PARTIDOS.PRESIDENTE%type;
  PRIMERAPELLIDO PARTIDOS.PRESIDENTE%type;
  SEGUNDOAPELLIDO PARTIDOS.PRESIDENTE%type;
BEGIN
  FOR ROW IN C LOOP
    NOMBRE:=SUBSTR(ROW.PRESIDENTE, 1, INSTR(ROW.PRESIDENTE, ' ') - 1);
    PRIMERAPELLIDO:=SUBSTR(ROW.PRESIDENTE, INSTR(ROW.PRESIDENTE, ' ') + 1, INSTR(ROW.PRESIDENTE, ' ', 1, 2) - INSTR(ROW.PRESIDENTE, ' ') - 1);
    SEGUNDOAPELLIDO:=SUBSTR(ROW.PRESIDENTE, INSTR(ROW.PRESIDENTE, ' ', 1, 2) + 1, LENGTH(ROW.PRESIDENTE) - INSTR(ROW.PRESIDENTE, ' ', 1, 2));
    IF SUBSTR(NOMBRE, -1)='o'
        AND SUBSTR(PRIMERAPELLIDO, -1)='o'
        AND SUBSTR(SEGUNDOAPELLIDO, -1)='o'
    THEN
      DBMS_OUTPUT.PUT_LINE(ROW.PRESIDENTE);
    END IF;
  END LOOP;
END;