SELECT V.NOMBRECOMPLETO, L.NOMBRE FROM VOTANTES V, LOCALIDADES L, CONSULTAS C
WHERE V.DNI=C.VOTANTE AND L.IDLOCALIDAD=V.LOCALIDAD AND L.NUMEROHABITANTES>'300000'
GROUP BY V.NOMBRECOMPLETO, L.NOMBRE;