SELECT V.NOMBRECOMPLETO, AVG(CD.CERTIDUMBRE) "MEDIAVOTACION SI" FROM VOTANTES V, CONSULTAS_DATOS CD, CONSULTAS C
WHERE V.DNI=C.VOTANTE AND C.IDCONSULTA=CD.CONSULTA AND CD.RESPUESTA='Si'
GROUP BY V.NOMBRECOMPLETO;