SELECT P.NOMBRECOMPLETO, COUNT(CD.PARTIDO) "CONTEO" FROM PARTIDOS P, CONSULTAS_DATOS CD
WHERE P.IDPARTIDO=CD.PARTIDO
GROUP BY P.NOMBRECOMPLETO
HAVING COUNT(CD.PARTIDO)>'10'
ORDER BY COUNT(CD.PARTIDO) ASC;