--Parte1
SELECT NOMBRECOMPLETO FROM VOTANTES
WHERE NOMBRECOMPLETO LIKE '%n';

SELECT DNI FROM VOTANTES
WHERE DNI LIKE '%5%5%5';

SELECT NOMBRECOMPLETO FROM VOTANTES
WHERE FECHANACIMIENTO>'1/01/90';

SELECT VOTANTES.NOMBRECOMPLETO, LOCALIDADES.NOMBRE FROM VOTANTES, LOCALIDADES
WHERE VOTANTES.LOCALIDAD=LOCALIDADES.IDLOCALIDAD AND LOCALIDADES.NUMEROHABITANTES>'300000';

SELECT VOTANTES.NOMBRECOMPLETO, PROVINCIAS.COMUNIDAD FROM VOTANTES, LOCALIDADES, PROVINCIAS
WHERE VOTANTES.LOCALIDAD=LOCALIDADES.IDLOCALIDAD AND LOCALIDADES.PROVINCIA=PROVINCIAS.IDPROVINCIA AND LOCALIDADES.NUMEROHABITANTES>'300000';

SELECT PARTIDO, COUNT(PARTIDO) FROM CONSULTAS_DATOS
GROUP BY PARTIDO;

SELECT P.NOMBRECOMPLETO, COUNT(CD.PARTIDO) "CONTEO" FROM PARTIDOS P, CONSULTAS_DATOS CD
WHERE P.IDPARTIDO=CD.PARTIDO
GROUP BY P.NOMBRECOMPLETO
HAVING COUNT(CD.PARTIDO)>'10'
ORDER BY COUNT(CD.PARTIDO) ASC;

SELECT P.NOMBRECOMPLETO, COUNT(CD.PARTIDO) "CONTEO" FROM PARTIDOS P, CONSULTAS_DATOS CD
WHERE P.IDPARTIDO=CD.PARTIDO AND CD.RESPUESTA='Si' AND CD.CERTIDUMBRE>'0,8'
GROUP BY P.NOMBRECOMPLETO;
-------------------------------------------------------------------------------------------------------------------
--Parte2
SELECT DNI, TELEFONO FROM VOTANTES
WHERE TELEFONO LIKE '%6%6%' AND TELEFONO NOT LIKE '%6%6%6%6%' ;

SELECT TELEFONO FROM VOTANTES
WHERE TELEFONO LIKE '%66%6%' AND TELEFONO NOT LIKE '%6%6%6%6%';

SELECT L.NOMBRE "LOCALIDAD", P.NOMBRE "PROVINCIA" FROM LOCALIDADES L, PROVINCIAS P
WHERE L.PROVINCIA=P.IDPROVINCIA AND SUBSTR(L.NUMEROHABITANTES,-1,1)=SUBSTR(P.IDPROVINCIA,-1,1);

SELECT NOMBRECOMPLETO, DNI, TELEFONO FROM VOTANTES
WHERE SUBSTR(DNI,-1,1)=SUBSTR(TELEFONO,-1,1);

SELECT NOMBRECOMPLETO, FECHANACIMIENTO FROM VOTANTES
WHERE NOMBRECOMPLETO LIKE '%S%' AND FECHANACIMIENTO<'12/02/90' OR NOMBRECOMPLETO LIKE '%s%' AND FECHANACIMIENTO<'12/02/90';

SELECT DISTINCT V.NOMBRECOMPLETO, V.DNI FROM VOTANTES V, CONSULTAS C
WHERE V.DNI=C.VOTANTE
ORDER BY V.DNI DESC;

SELECT C.VOTANTE, V.NOMBRECOMPLETO, COUNT(C.VOTANTE) "VECES" FROM CONSULTAS C, VOTANTES V
WHERE C.VOTANTE=V.DNI
GROUP BY C.VOTANTE, V.NOMBRECOMPLETO
HAVING COUNT(C.VOTANTE)>'3';

SELECT V.NOMBRECOMPLETO, COUNT(C.VOTANTE) "VECES" FROM VOTANTES V, CONSULTAS C 
WHERE V.DNI=C.VOTANTE
GROUP BY V.NOMBRECOMPLETO
HAVING COUNT(C.VOTANTE)>'3'
ORDER BY COUNT(C.VOTANTE) ASC;

SELECT V.NOMBRECOMPLETO, L.NOMBRE FROM VOTANTES V, LOCALIDADES L, CONSULTAS C
WHERE V.DNI=C.VOTANTE AND L.IDLOCALIDAD=V.LOCALIDAD AND L.NUMEROHABITANTES>'300000'
GROUP BY V.NOMBRECOMPLETO, L.NOMBRE;

SELECT P.NOMBRECOMPLETO, MAX(CD.CERTIDUMBRE) "MXCERT"  FROM PARTIDOS P, CONSULTAS_DATOS CD
WHERE P.IDPARTIDO=CD.PARTIDO
GROUP BY P.NOMBRECOMPLETO
ORDER BY MAX(CD.CERTIDUMBRE) DESC;

SELECT V.NOMBRECOMPLETO, AVG(CD.CERTIDUMBRE) "MEDIAVOTACION SI" FROM VOTANTES V, CONSULTAS_DATOS CD, CONSULTAS C
WHERE V.DNI=C.VOTANTE AND C.IDCONSULTA=CD.CONSULTA AND CD.RESPUESTA='Si'
GROUP BY V.NOMBRECOMPLETO;

SELECT V.NOMBRECOMPLETO, AVG(CD.CERTIDUMBRE) "MEDIAVOTACION SI" FROM VOTANTES V, CONSULTAS_DATOS CD, CONSULTAS C
WHERE V.DNI=C.VOTANTE AND C.IDCONSULTA=CD.CONSULTA AND CD.RESPUESTA='Si'
GROUP BY V.NOMBRECOMPLETO
HAVING AVG(CD.CERTIDUMBRE)>'0,5' AND AVG(CD.CERTIDUMBRE)<'0,8';

SELECT P.NOMBRECOMPLETO, AVG(CD.CERTIDUMBRE) FROM PARTIDOS P, CONSULTAS_DATOS CD
WHERE P.IDPARTIDO=CD.PARTIDO AND CD.RESPUESTA='No'
GROUP BY P.NOMBRECOMPLETO
HAVING AVG(CD.CERTIDUMBRE)>'0,6';






