SET SERVEROUTPUT ON;
DECLARE
  FECHAMIN VOTANTES.FECHANACIMIENTO%TYPE;
  FECHAMAX VOTANTES.FECHANACIMIENTO%TYPE;
  NOMBREMIN VOTANTES.NOMBRECOMPLETO%TYPE;
  NOMBREMAX VOTANTES.NOMBRECOMPLETO%TYPE;
  DIFERENCIA NUMBER(2);
BEGIN
  SELECT A.FECHANACIMIENTO, A.NOMBRECOMPLETO, B.FECHANACIMIENTO, B.NOMBRECOMPLETO
  INTO FECHAMIN, NOMBREMIN, FECHAMAX, NOMBREMAX
  FROM VOTANTES A, VOTANTES B
  WHERE A.FECHANACIMIENTO=(SELECT MIN(FECHANACIMIENTO) FROM VOTANTES)
  AND B.FECHANACIMIENTO=(SELECT MAX(FECHANACIMIENTO) FROM VOTANTES); 
  DIFERENCIA:=ROUND((FECHAMAX-FECHAMIN)/365);
  DBMS_OUTPUT.PUT_LINE('Persona con más edad: ' || NOMBREMIN ||' ' || FECHAMIN);
  DBMS_OUTPUT.PUT_LINE('Persona con menos edad: ' || NOMBREMAX ||' ' || FECHAMAX);
  DBMS_OUTPUT.PUT_LINE('La diferencia es: ' || DIFERENCIA || ' años');
END;