SET SERVEROUTPUT ON;
DECLARE
  NOMBRE VOTANTES.NOMBRECOMPLETO%TYPE;
  MYEMAIL VOTANTES.EMAIL%TYPE;
  MYDNI NUMBER := 30983712;
BEGIN
  SELECT NOMBRECOMPLETO, EMAIL 
  INTO NOMBRE, MYEMAIL 
  FROM VOTANTES 
  WHERE DNI=MYDNI;
  DBMS_OUTPUT.PUT_LINE(NOMBRE||' con correo: '|| MYEMAIL);
END;