SET SERVEROUTPUT ON;
DECLARE
  CURSOR C IS 
  SELECT CD.CERTIDUMBRE, P.NOMBRECOMPLETO, CD.RESPUESTA
  FROM CONSULTAS_DATOS CD, PARTIDOS P
  WHERE P.IDPARTIDO=CD.PARTIDO
  ORDER BY CD.CERTIDUMBRE DESC;
  MEDIA NUMBER:=0;
  COUNTER NUMBER:=0;
BEGIN
  FOR ROW IN C LOOP 
    MEDIA:=MEDIA+ROW.CERTIDUMBRE;
    COUNTER:=COUNTER+1;
  END LOOP;
  MEDIA:=ROUND(MEDIA/COUNTER, 3);
  DBMS_OUTPUT.PUT_LINE('La media de la certidumbre es: ' || MEDIA);
  FOR ROW IN C LOOP
    IF ROW.RESPUESTA='Si' 
      AND ROW.CERTIDUMBRE>MEDIA
      THEN
      DBMS_OUTPUT.PUT_LINE(ROW.NOMBRECOMPLETO|| ' ' || ROW.CERTIDUMBRE);
    END IF;
  END LOOP;
END;
