SET SERVEROUTPUT ON;
CREATE OR REPLACE TRIGGER TRIGGER2
BEFORE UPDATE ON LOCALIDADES FOR EACH ROW
BEGIN
  IF :NEW.NUMEROHABITANTES<1 OR :NEW.NUMEROHABITANTES>40000000 THEN
    :NEW.NUMEROHABITANTES:=:OLD.NUMEROHABITANTES;
  END IF;
END;

UPDATE LOCALIDADES SET NUMEROHABITANTES=0 WHERE IDLOCALIDAD=1;