SET SERVEROUTPUT ON;
CREATE OR REPLACE TRIGGER TRIGGER3
BEFORE UPDATE ON CONSULTAS FOR EACH ROW
BEGIN
  IF :NEW.FECHA>SYSDATE THEN
    INSERT INTO AUDIT_TABLE VALUES('Hubo cambios en la fecha, de ' || :NEW.FECHA || ' a ' || SYSDATE, 'CONSULTAS');
    :NEW.FECHA:=SYSDATE;
  END IF;
END;

UPDATE CONSULTAS SET FECHA='22/4/2021' WHERE IDCONSULTA=1;